### ISSUE TITLE
Cloning a SnowflakeGenerator struct

### ISSUE THREAD

**Issue by GenericNerd** [photowey/snowflake#16]
Since the Clone trait is not implemented, this doesn't seem to be possible at the moment. Is it possible to add an `Arc` around the `AttomicU64` structs of the `sequence` and `last_timestamp` fields. This seems to be the path of least resistance.

Great crate regardless!

**Comment by photowey** [comment]
OK. I will solve it as soon as possible. Sorry for the late reply.

**Comment by photowey** [comment]
@GenericNerd The latest version v0.3.6 of issue#16 has been released. Refer to crates.io. Thx.

**Comment by GenericNerd** [comment]
Thank you so much!
